### ISSUE TITLE
Fatal error: Call to a member function set() on null

### ISSUE THREAD

**Issue by avarx** [FluidTYPO3/site#8] opened 2015-07-20 12:47 UTC
TYPO3 version: 6.2.14
Extension version: 1.3.3

When creating a new extension I get different errors like:
-->Fatal error: Call to a member function set() on null
-->Extension testTemplate is not available 
-->The action "welcome" (controller "Distribution") is not allowed by this plugin

In Slack there is one more user with the same errors.
Let me know if you need more information.

Edit: After some debugging I guess it's a mapping Problem.

**Comment by xf-** [comment] 2015-07-23 23:08
Hi,
looks like thid is no bug. The problem is welcome works only in preconfigured Package.
If you press save in settings, it will throw that error.

We are not the only one with that problem according to google.

I know no workaround.

**Comment by xf-** [comment] 2015-07-23 23:09
if anybody finds something in T3 to avoid this comment again.
I will close this until then.

**Closed by xf-** 2015-07-23 23:09 UTC
